/// Registering  User

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Pencil98",
  "name": "Pencil",
  "password": "Pencil9898",
  "gender": "male",
  "location": "India"
}
###

POST http://localhost:3000/login
Content-Type: application/json


{
  "username": "Pencil98",
  "password": "Pencil9898"
}

###